# Parse SWC files and extract neuron tree structures
import os
import pandas as pd
from joblib import Parallel, delayed
from neuroutils.meta.mapping import extract_neuron_id
from neuroutils.meta.neuron import get_neuron_meta
from neuroutils.config.settings import DEFAULT_RESOLUTION_UNIT, DEFAULT_NUM_THREADS
from collections import defaultdict, deque
from tqdm import tqdm
import networkx as nx
import numpy as np

# def load_swc(swc_file):
#     swc = pd.read_csv(swc_file, sep=' ', header=None, comment='#')
#
#     if(swc_file.endswith(".swc")):
#         swc.columns = ['n', 'type', 'x', 'y', 'z', 'r', 'parent']
#         # 数据类型转换
#         swc['n'] = swc['n'].astype(int)
#         swc['type'] = swc['type'].astype(int)
#         swc['x'] = swc['x'].astype(float)
#         swc['y'] = swc['y'].astype(float)
#         swc['z'] = swc['z'].astype(float)
#         swc['r'] = swc['r'].astype(float)
#         swc['parent'] = swc['parent'].astype(int)
#
#         try:
#             neuron_id = extract_neuron_id(swc_file)
#         except Exception as e:
#             neuron_id = "unknown"
#         swc['neuron_id'] = neuron_id
#     elif(swc_file.endswith(".eswc")):
#         ##n,type,x,y,z,radius,parent,seg_id,level,mode,timestamp,feature_value
#         swc.columns = ['n', 'type', 'x', 'y', 'z', 'r', 'parent', 'seg_id', 'level', 'mode', 'timestamp', 'feature_value']
#         # 数据类型转换
#         swc['n'] = swc['n'].astype(int)
#         swc['type'] = swc['type'].astype(int)
#         swc['x'] = swc['x'].astype(float)
#         swc['y'] = swc['y'].astype(float)
#         swc['z'] = swc['z'].astype(float)
#         swc['r'] = swc['r'].astype(float)
#         swc['parent'] = swc['parent'].astype(int)
#         swc['seg_id'] = swc['seg_id'].astype(int)
#         swc['level'] = swc['level'].astype(int)
#         swc['mode'] = swc['mode'].astype(int)
#         swc['timestamp'] = swc['timestamp'].astype(int)
#         swc['feature_value'] = swc['feature_value'].astype(float)
#
#         try:
#             neuron_id = extract_neuron_id(swc_file)
#         except Exception as e:
#             neuron_id = "unknown"
#         swc['neuron_id'] = neuron_id
#
#     return swc


def load_swc(swc_file):
    if(swc_file.endswith(".swc")):
        swc = pd.read_csv(
            swc_file,
            sep=' ',
            header=None,
            comment='#',
            dtype={
                0: int,
                1: int,
                2: float,
                3: float,
                4: float,
                5: float,
                6: int
            }
        )

        swc.columns = ['n', 'type', 'x', 'y', 'z', 'r', 'parent']

        try:
            neuron_id = extract_neuron_id(swc_file)
        except Exception:
            neuron_id = "unknown"
        swc['neuron_id'] = neuron_id

    elif(swc_file.endswith(".eswc")):
        swc = pd.read_csv(
            swc_file,
            sep=' ',
            header=None,
            comment='#',
            dtype={
                0: int,
                1: int,
                2: float,
                3: float,
                4: float,
                5: float,
                6: int,
                7: int,
                8: int,
                9: int,
                10: int,
                11: float
            }
        )

        swc.columns = ['n', 'type', 'x', 'y', 'z', 'r', 'parent',
                       'seg_id', 'level', 'mode', 'timestamp', 'feature_value']

        try:
            neuron_id = extract_neuron_id(swc_file)
        except Exception:
            neuron_id = "unknown"
        swc['neuron_id'] = neuron_id

    return swc

def save_swc(swc, output_file):

    # 1. 只保留标准 SWC 列
    swc = swc[['n', 'type', 'x', 'y', 'z', 'r', 'parent']]

    # 2. 按 n 排序
    swc = swc.sort_values(by='n').reset_index(drop=True)

    # 3. 转换为正确的数据类型
    swc = swc.astype({
        'n': int,
        'type': int,
        'x': float,
        'y': float,
        'z': float,
        'r': float,
        'parent': int,
    })

    # 4. 写入 SWC 文件
    with open(output_file, 'w') as f:
        f.write('# Generated by Neuroutils\n')
        f.write('#\n')
        f.write('# id type x y z radius parent\n')
        swc.to_csv(f, sep=' ', index=False, header=False)

# def save_swc(swc, output_file):
#     # print(swc)
#     swc = swc[['n', 'type', 'x', 'y', 'z', 'r', 'parent']]
#     # Save the SWC DataFrame to a file
#     with open(output_file, 'w') as f:
#         f.write('# Generated by Neuroutils\n')
#         f.write('#\n')
#         f.write('# id type x y z radius parent\n')
#         swc.to_csv(f, sep=' ', index=False, header=False)
#
# def rescale_swc(swc, xy_resolution=None, z_resolution=None):
#     if(xy_resolution is None) and (z_resolution is None):
#         meta = get_neuron_meta(swc['neuron_id'].iloc[0])
#         xy_resolution = float(meta['xy_resolution']) / DEFAULT_RESOLUTION_UNIT
#         z_resolution = float(meta['z_resolution']) / DEFAULT_RESOLUTION_UNIT
#     swc['x'] *= xy_resolution
#     swc['y'] *= xy_resolution
#     swc['z'] *= z_resolution
#     return swc


def swc_to_graph(swc):
    G = nx.Graph()

    # 添加节点
    for _, row in swc.iterrows():
        G.add_node(row['n'], **row.to_dict())

    # 添加边（忽略 parent = -1）
    for _, row in swc.iterrows():
        n = row['n']
        p = row['parent']
        if p != -1:
            G.add_edge(n, p)

    return G


def graph_to_swc(G, root):
    visited = set()
    queue = [(root, -1)]
    out = []

    while queue:
        node, parent = queue.pop(0)
        attr = G.nodes[node].copy()

        attr['n'] = node
        attr['parent'] = parent
        out.append(attr)

        visited.add(node)

        for nb in G.neighbors(node):
            if nb not in visited:
                queue.append((nb, node))

    return pd.DataFrame(out)


def load_swc_as_graph(swc_file):
    swc = load_swc(swc_file)
    G = swc_to_graph(swc)
    return G


def save_graph_as_swc(G, root, output_file):
    swc = graph_to_swc(G, root)
    save_swc(swc, output_file)


# def is_valid_tree_swc(swc_df):
#     # 条件1: 唯一根节点
#     roots = swc_df[swc_df['parent'] == -1]
#     if len(roots) != 1:
#         print("无效：根节点数量不为1")
#         return False
#
#     # 条件2: 节点编号唯一
#     if swc_df['n'].duplicated().any():
#         print("无效：节点编号重复")
#         return False
#
#     node_ids = set(swc_df['n'])
#     parent_ids = set(swc_df['parent'])
#     if not parent_ids.issubset(node_ids.union({-1})):
#         print("无效：存在未知父节点")
#         return False
#
#     # 构建邻接表
#     graph = defaultdict(list)
#     root_id = roots.iloc[0]['n']
#     for _, row in swc_df.iterrows():
#         if row['parent'] != -1:
#             graph[row['parent']].append(row['n'])
#
#     # 条件3+4: 从根节点出发做DFS，判断连通性和无环性
#     visited = set()
#     stack = [(root_id, -1)]
#     while stack:
#         current, parent = stack.pop()
#         if current in visited:
#             print("无效：图中存在环")
#             return False
#         visited.add(current)
#         for child in graph[current]:
#             if child != parent:
#                 stack.append((child, current))
#
#     if visited != node_ids:
#         print("无效：图不连通")
#         return False
#
#     return True


def is_valid_tree_swc(swc_df):
    """
    全面校验 SWC 文件，包含结构错误检查和生物学合理性警告。

    Returns:
        tuple: (is_valid (bool), messages (list))
        - is_valid: False 表示存在结构性硬伤，True 表示结构正常。
        - messages: 包含 Error 和 Warning 的详细文本列表。
    """
    messages = []

    # ==========================================
    # Part 1: 硬伤检查 (Structural Errors)
    # 任何一项失败都会直接返回 False
    # ==========================================

    # 1. 唯一根节点检查
    roots = swc_df[swc_df['parent'] == -1]
    # print(roots)
    if len(roots) != 1:
        messages.append(f"[Error] 根节点数量不为 1 (发现 {len(roots)} 个)")
        return False, messages

    root_row = roots.iloc[0]
    root_id = root_row['n']

    # 2. 节点编号唯一性
    if swc_df['n'].duplicated().any():
        dup_ids = swc_df[swc_df['n'].duplicated()]['n'].unique()
        messages.append(f"[Error] 存在重复的节点编号: {dup_ids[:5]}...")
        return False, messages

    # 3. 父节点引用有效性
    node_ids = set(swc_df['n'])
    parent_ids = set(swc_df['parent'])
    if not (parent_ids - {-1}).issubset(node_ids):
        missing = (parent_ids - {-1}) - node_ids
        messages.append(f"[Error] 父节点指向了不存在的 ID: {list(missing)[:5]}...")
        return False, messages

    # --- 构建图结构 (高性能版) ---
    graph = defaultdict(list)     # Parent -> Children
    nodes_map = {}                # ID -> (x, y, z, r, type) 方便后续计算

    # 使用 numpy 数组加速迭代
    data_matrix = swc_df[['n', 'type', 'x', 'y', 'z', 'r', 'parent']].values

    for row in data_matrix:
        n, t, x, y, z, r, p = row
        n, p, t = int(n), int(p), int(t)
        nodes_map[n] = {'pos': np.array([x, y, z]), 'r': r, 'type': t}
        if p != -1:
            graph[p].append(n)

    # 4. 连通性与环路检查 (DFS)
    visited = set()
    stack = [root_id]

    while stack:
        current = stack.pop()
        if current in visited:
            messages.append(f"[Error] 图中存在环或汇聚节点 (节点 {current})")
            return False, messages
        visited.add(current)

        if current in graph:
            for child in graph[current]:
                stack.append(child)

    if len(visited) != len(node_ids):
        messages.append(f"[Error] 图不连通 (共有 {len(node_ids)} 节点, 根节点只能到达 {len(visited)})")
        return False, messages

    # ==========================================
    # Part 2: 软伤检查 (Warnings)
    # 结构合法，但形态可能异常
    # ==========================================

    # # Warning 1: 根节点半径检查 (通常 Soma 半径最大)
    # root_r = nodes_map[root_id]['r']
    # max_r = swc_df['r'].max()
    # # 允许一点点浮点误差，或者严格比较
    # if root_r < max_r:
    #     max_r_node = swc_df.loc[swc_df['r'].idxmax(), 'n']
    #     messages.append(f"[Warning] 根节点不是最粗的。Root R={root_r:.3f}, Max R={max_r:.3f} (at node {max_r_node})")

    # Warning 2: 根节点度数检查 (Degree)
    # 根节点在树中没有父节点，所以 Degree = len(children)
    # print(graph[root_id])
    root_children_count = len(graph[root_id])
    if root_children_count < 3:
        messages.append(f"[Warning] 根节点的分支度过低 (Children={root_children_count})。建议 Degree >= 3")

    # Warning 4: 极小/负半径检查
    invalid_r_count = (swc_df['r'] <= 0).sum()
    if invalid_r_count > 0:
        messages.append(f"[Warning] 发现 {invalid_r_count} 个节点的半径 <= 0")

    # Warning 5: 跳跃检测 (Jump Detection) - 检测父子节点距离是否过大
    # 这是一个非常实用的检查，防止重建时产生的飞线
    jump_threshold = 50.0  # 阈值，单位通常是微米，可根据数据分辨率调整

    jumps = []
    for child_id, props in nodes_map.items():
        # 找到父节点ID (需要在原始df或map里反查，这里我们可以直接利用 swc_df)
        # 为了速度，我们在循环外构建一个 parent_map
        pass

        # 为了高性能计算 Jump，利用 Pandas 向量化计算
    # 将父节点的坐标 map 到当前行
    swc_df['parent_x'] = swc_df['parent'].map(lambda pid: nodes_map[pid]['pos'][0] if pid != -1 else np.nan)
    swc_df['parent_y'] = swc_df['parent'].map(lambda pid: nodes_map[pid]['pos'][1] if pid != -1 else np.nan)
    swc_df['parent_z'] = swc_df['parent'].map(lambda pid: nodes_map[pid]['pos'][2] if pid != -1 else np.nan)

    # 计算欧氏距离
    dist = np.sqrt(
        (swc_df['x'] - swc_df['parent_x'])**2 +
        (swc_df['y'] - swc_df['parent_y'])**2 +
        (swc_df['z'] - swc_df['parent_z'])**2
    )

    # 找出距离过大的点
    large_jumps = dist[dist > jump_threshold]
    if not large_jumps.empty:
        max_jump = large_jumps.max()
        messages.append(f"[Warning] 发现 {len(large_jumps)} 处父子节点间距过大 (Max Jump = {max_jump:.2f} um)")

    if(messages):
        print(f"SWC ID {swc_df['neuron_id'].iloc[0]} 存在以下问题：")
        for msg in messages:
            print(msg)
    return True, messages

def is_valid_swc_dir(swc_dir):
    swc_files = [os.path.join(swc_dir, f) for f in os.listdir(swc_dir) if f.endswith('.swc')]
    Parallel(n_jobs=DEFAULT_NUM_THREADS)(delayed(is_valid_tree_swc)(load_swc(swc_file)) for swc_file in tqdm(swc_files))


if __name__ == "__main__":
    # swc_dir = "/data/kfchen/trace_ws/paper_auto_human_neuron_recon/swc_label/1um_swc_lab_resample_prune"
    # is_valid_swc_dir(swc_dir)
    swc_file = "/home/lyf/Research/publication/humain10k/HumanMorphoMap/h01-guided-reconstruction/data/manual_resampled1um/3167.swc"
    is_valid_tree_swc(load_swc(swc_file))